// pack.mjs — the gateway's own build step: inlines app/src/guide-spec.mjs into a
// self-contained copy, so the deployed service never depends on a sibling app/ folder
// existing at runtime. Dev keeps spec.mjs's one-line re-export checked in (spec.mjs:1-3
// says as much); this script only ever writes into a throwaway build or a test's temp file.
//
// The live gateway's healthz already answers today (measured 2026-09-26) with the CURRENT
// re-export in place, because its Railway service's root directory is "gateway" while
// `railway up` is run from the REPO ROOT (see the note in this repo's PR history) - so the
// relative import ../app/src/guide-spec.mjs already resolves at runtime. This script exists
// for the case that stops being true (a git-connected deploy, a different root, a registry
// that only ever sees this folder) and, right now, as the thing gateway/tests/selftest.mjs
// packs and diffs against the app's live exports - so a stale gateway copy is a red test,
// never a silent surprise on the next redeploy.
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const HERE = path.dirname(fileURLToPath(import.meta.url));
const SOURCE = path.join(HERE, "..", "app", "src", "guide-spec.mjs");
const BANNER = "// GENERATED by gateway/pack.mjs from app/src/guide-spec.mjs - do not hand-edit.\n"
  + "// Dev keeps the one-line re-export (see this repo's spec.mjs); this copy exists only\n"
  + "// inside a deploy build (or a test's temp file) and is overwritten on the next pack.\n\n";

// Inlines the app's guide-spec.mjs verbatim. guide-spec.mjs is deliberately self-contained
// (zero imports of its own - it's the ONE definition shared by the app and this gateway), so
// packing it is a straight copy; this guard fails loudly the day that stops being true rather
// than silently shipping a spec.mjs whose imports resolve to nothing in the deploy bundle.
export function pack() {
  const src = fs.readFileSync(SOURCE, "utf8");
  if (/^\s*import\b/m.test(src)) {
    throw new Error("guide-spec.mjs now has an import - pack.mjs only inlines a standalone file; teach it to resolve imports before packing, or this deploy copy will silently reference nothing");
  }
  return BANNER + src;
}

// CLI: node pack.mjs [outFile]  (default: gateway/spec.mjs - the deploy build step)
if (process.argv[1] && import.meta.url.endsWith(path.basename(process.argv[1]))) {
  const out = process.argv[2] ? path.resolve(process.argv[2]) : path.join(HERE, "spec.mjs");
  fs.writeFileSync(out, pack());
  console.log(`packed ${path.relative(process.cwd(), SOURCE)} -> ${path.relative(process.cwd(), out)}`);
}
